volumes:
  db-data:


services:
  app:
    image: sqlboiler-migrate-sample
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1323:1323"
    volumes:
      - .:/app
    command: tail -f /dev/null
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
