FROM golang:1.21
ENV TZ Asia/Tokyo
WORKDIR /app
# for golang extension
RUN go install github.com/ramya-rao-a/go-outline@latest && \
  go install golang.org/x/tools/gopls@latest && \
  go install golang.org/x/tools/cmd/goimports@latest && \
  go install honnef.co/go/tools/cmd/staticcheck@latest && \
  go install github.com/cosmtrek/air@latest && \
  go install github.com/go-delve/delve/cmd/dlv@latest
